apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-route
  namespace: argocd
spec:
  entryPoints:
    - web  # Ensure this matches your Traefik entry point
  routes:
    - match: Host(`argocd.example.com`)  # This matches all requests
      kind: Rule
      services:
        - name: argocd-server 
          namespace: argocd  # Correctly references the namespace
          port: 80